# Physical NIC for LAN + SRV VLAN
lan_iface: enp16s0

# VLAN for SRV traffic
srv_vlan_id: 10

# LAN details
lan_network_name: lan-net

# SRV details
srv_address: 10.0.0.2/24
srv_gateway: 10.0.0.1
srv_network_name: srv-net