- name: Install KDE Plasma desktop
  apt:
    name:
      - kde-plasma-desktop
      - sddm
      - vbetool
    state: present
    update_cache: yes

- name: Set multi-user.target as default (prevent graphical.target from being default)
  file:
    src: /lib/systemd/system/multi-user.target
    dest: /etc/systemd/system/default.target
    state: link
    force: yes

- name: Mask PowerDevil for all users - to not interfere with the tardis server part still running in the background (or acpid)
  ansible.builtin.systemd:
    name: plasma-powerdevil.service
    scope: global
    masked: true

- import_tasks: startstop.yml
- import_tasks: sddm.yml
- import_tasks: lockscreen-monitor-standby.yml
